---
title: "Chapter 4"
author: "Christopher Chan"
date: "`r format(Sys.time(), '%H:%M %d %B %Y')`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(brms)
```


### 4.1
```{r}
set.seed(4)

pos <- 
  replicate(100, runif(16, -1, 1)) %>%
  as_tibble() %>%
  rbind(0, .) %>%
  mutate(step = 0:16) %>%
  gather(key, value, -step) %>%
  mutate(person = rep(1:100, each = 17)) %>%
  group_by(person) %>%
  mutate(position = cumsum(value)) %>%
  ungroup()

glimpse(pos)
```

```{r}
ggplot(pos, aes(step, position, group=person)) +
  geom_line(aes(color = person < 2, alpha = person < 2)) + 
  geom_vline(xintercept = c(4, 8, 16), linetype = 2) +
  scale_color_manual(values = c("skyblue4", "black")) +
  scale_alpha_manual(values = c(1/5, 1)) +
  scale_x_continuous("step number", breaks = c(0, 4, 8, 12, 16)) +
  theme(legend.position = "none")
```

### 4.2

### 4.3
- Define distributions by $\mu$ and $\sigma$ and rank by plausibility, aka our 
posterior plausibility.
- The model:  
$h_i$ ~ Normal$(\mu, \sigma)$ [likelihood]  
$\mu$ ~ Normal(178, 20) [$\mu$ prior]  
$\sigma$ ~ Uniform(0, 50) [$\sigma$ prior]  

```{r}
df <- read_delim('data/Howell1.csv', delim = ';')

df2 <-
  df %>%
  filter(age >= 18)
```

```{r}
# Plotting priors
ggplot(tibble(x = seq(100, 250, by = 0.1)),
       aes(x, dnorm(x, mean = 178, sd = 20))) +
  geom_line() +
  ggtitle("Prior density")


ggplot(tibble(x = seq(-10, 60, by = 0.1)),
       aes(x, dunif(x, 0, 50))) +
  geom_line() +
  ggtitle('Prior sigmas')

```

Drawing samples from prior distribution
```{r}
set.seed(4)

n <- 1e4

tibble(sample_mu = rnorm(n, mean = 178, sd = 20),
       sample_sigma = runif(n, min = 0, max = 50)) %>%
  mutate(x = rnorm(n, mean = sample_mu, sd = sample_sigma)) %>%
  ggplot(aes(x)) +
    geom_density(fill = 'black') +
    scale_y_continuous() +
      labs(subtitle = expression(paste("Prior predictive distribution for ", 
                                       italic(h[i]))), x = NULL)


# larger sigma
tibble(sample_mu = rnorm(n, mean = 178, sd = 20),
       sample_sigma = runif(n, min = 0, max = 100)) %>%
  mutate(x = rnorm(n, mean = sample_mu, sd = sample_sigma)) %>%
  ggplot(aes(x)) +
    geom_density(fill = 'black') +
    scale_y_continuous() +
      labs(subtitle = expression(paste("Prior predictive distribution for ", 
                                       italic(h[i]))), x = NULL)
```

```{r}
n <- 200

d_grid <- tibble(mu = seq(140, 160, length.out = n),
                 sigma = seq(4, 9, length.out = n)) %>%
  expand(mu, sigma)

grid_function <- function(mu, sigma){
  dnorm(df2$height, mu, sigma, log = TRUE) %>%
  sum()
}

d_grid <- 
  d_grid %>%
  mutate(log_likelihood = map2(mu, sigma, grid_function)) %>%
  unnest() %>%
  mutate(prior_mu = dnorm(mu, mean = 178, sd = 20, log = TRUE),
         prior_sigma = dunif(sigma, 0, 50, log = TRUE)) %>%
  mutate(product = log_likelihood + prior_mu + prior_sigma) %>%
  mutate(probability = exp(product - max(product)))

head(d_grid)
```

```{r}
ggplot(d_grid, aes(mu, sigma, z = probability)) +
  geom_contour() +
  labs(x = expression(mu),
       y = expression(sigma)) +
  coord_cartesian(xlim = range(d_grid$mu),
                  ylim = range(d_grid$sigma))
```

Sampling posterior
```{r}
set.seed(4)

d_grid_sample <- 
  d_grid %>%
  sample_n(1e4, replace = TRUE, weight = probability)

ggplot(d_grid_sample, aes(mu, sigma)) +
  geom_point(alpha = 0.05)
```

Distribution/confidence in posterior
```{r}
d_grid_sample %>%
  select(mu, sigma) %>%
  gather() %>%
  
  ggplot(aes(value)) +
    geom_density(fill = 'grey33') +
    facet_wrap(~key, scales = 'free')
```

Modelling with brm()
```{r}
b4.1 <- brm(data = df2, family = gaussian,
            height ~ 1,
            prior = c(prior(normal(178, 20), class = Intercept),
                      prior(uniform(0, 50), class = sigma)),
            iter = 31000, warmup = 30000, chain = 4, cores = 4, seed = 4)
```





